const languages = [
    {
     no: "0",
     name: "Auto",
     native: "Detect",
     code: "auto",  
    },
    {
     no: "1",
     name: "Abkhaz",
     native: "Аҧсуа",
     code: "ab",  
    },
    {
     no: "2",
     name: "Afar",
     native: "Afaraf",
     code: "aa",  
    },
    {
     no: "3",
     name: "Afrikaans",
     native: "Afrikaans",
     code: "af",  
    },
    {
     no: "4",
     name: "Akan",
     native: "Akan",
     code: "ak",  
    },
    {
     no: "5",
     name: "Albanian",
     native: "Shqip",
     code: "sq",  
    },
    {
     no: "6",
     name: "Amharic",
     native: "አማርኛ",
     code: "am",  
    },
    {
     no: "7",
     name: "Arabic",
     native: "العربية",
     code: "ar",  
    },
    {
     no: "8",
     name: "Aragonese",
     native: "Aragonés",
     code: "an",  
    },
    {
     no: "9",
     name: "Armenian",
     native: "Հայերեն",
     code: "hy",  
    },
    {
     no: "10",
     name: "Assamese",
     native: "অসমীয়া",
     code: "as",  
    },
    {
     no: "11",
     name: "Avaric",
     native: "авар мацӀ, магӀарул мацӀ",
     code: "as",  
    },
    {
     no: "12",
     name: "Avestan",
     native: "avesta",
     code: "ae",  
    },
    {
     no: "13",
     name: "Aymara",
     native: "aymar aru",
     code: "ay",  
    },
    {
     no: "14",
     name: "Azerbaijani",
     native: "Azərbaycan dili",
     code: "az",  
    },
    {
     no: "15",
     name: "Bambara",
     native: "bamanankan",
     code: "bm",  
    },
    {
     no: "16",
     name: "Bashkir",
     native: "башҡорт теле",
     code: "ba",  
    },
    {
     no: "17",
     name: "Basque",
     native: "euskara, euskera",
     code: "eu",  
    },
    {
     no: "18",
     name: "Belarusian",
     native: "Беларуская",
     code: "be",  
    },
    {
     no: "19",
     name: "Bengali",
     native: "বাংলা",
     code: "bn",  
    },
    {
     no: "20",
     name: "Bihari",
     native: "भोजपुरी",
     code: "bh",  
    },
    {
     no: "21",
     name: "Bislama",
     native: "Bislama",
     code: "bi",  
    },
    {
     no: "22",
     name: "Bosnian",
     native: "bosanski jezik",
     code: "bs",  
    },
    {
     no: "23",
     name: "Breton",
     native: "brezhoneg",
     code: "br",  
    },
    {
     no: "24",
     name: "Bulgarian",
     native: "български език",
     code: "bg",  
    },
    {
     no: "25",
     name: "Burmese",
     native: "ဗမာစာ",
     code: "my",  
    },
    {
     no: "26",
     name: "Catalan; Valencian",
     native: "català, valencià",
     code: "ca",  
    },
    {
     no: "27",
     name: "Chamorro",
     native: "Chamoru",
     code: "ch",  
    },
    {
     no: "28",
     name: "Chechen",
     native: "нохчийн мотт",
     code: "ce",  
    },
    {
     no: "29",
     name: "Chichewa; Chewa; Nyanja",
     native: "chiCheŵa, chinyanja",
     code: "ny",  
    },
    {
     no: "30",
     name: "Chinese",
     native: "中文 (Zhōngwén), 汉语, 漢語",
     code: "zh",  
    },
    {
     no: "31",
     name: "Chuvash",
     native: "чӑваш чӗлхи",
     code: "cv",  
    },
    {
     no: "32",
     name: "Cornish",
     native: "Kernewek",
     code: "kw",  
    },
    {
     no: "33",
     name: "Corsican",
     native: "corsu, lingua corsa",
     code: "co",  
    },
    {
     no: "34",
     name: "Cree",
     native: "ᓀᐦᐃᔭᐍᐏᐣ",
     code: "cr",  
    },
    {
     no: "35",
     name: "Croatian",
     native: "Hrvatski",
     code: "hr",  
    },
    {
     no: "36",
     name: "Czech",
     native: "čeština, čeština, český jazyk",
     code: "cs",  
    },
    {
     no: "37",
     name: "Danish",
     native: "dansk",
     code: "da",  
    },
    {
     no: "38",
     name: "Divehi; Dhivehi; Maldivian",
     native: "ދިވެހި",
     code: "dv",  
    },
    {
     no: "39",
     name: "Dutch",
     native: "Nederlands, Vlaams",
     code: "nl",  
    },
    {
     no: "40",
     name: "English",
     native: "English",
     code: "en",  
    },
    {
     no: "41",
     name: "Esperanto",
     native: "Esperanto",
     code: "eo",  
    },
    {
     no: "42",
     name: "Estonian",
     native: "eesti, eesti keel",
     code: "et",  
    },
    {
     no: "43",
     name: "Ewe",
     native: "Eʋegbe",
     code: "ee",  
    },
    {
     no: "44",
     name: "Faroese",
     native: "føroyskt",
     code: "fo",  
    },
    {
     no: "45",
     name: "Fijian",
     native: "Vosa Vakaviti",
     code: "fj",  
    },
    {
     no: "46",
     name: "Finnish",
     native: "suomi, suomen kieli",
     code: "fi",  
    },
    {
     no: "47",
     name: "French",
     native: "français, langue française",
     code: "fr",  
    },
    {
     no: "48",
     name: "Fula; Fulah; Pulaar; Pular",
     native: "Fulfulde, Pulaar, Pular",
     code: "ff",  
    },
    {
     no: "49",
     name: "Galician; Galiciano",
     native: "Galego",
     code: "gl",  
    },
    {
     no: "50",
     name: "Georgian",
     native: "ქართული",
     code: "ka",  
    },
    {
     no: "51",
     name: "German",
     native: "Deutsch",
     code: "de",  
    },
    {
     no: "52",
     name: "Greek",
     native: "Ελληνικά",
     code: "el",  
    },
    {
     no: "53",
     name: "Guaraní",
     native: "Avañe'ẽ",
     code: "gn",  
    },
    {
     no: "54",
     name: "Gujarati",
     native: "ગુજરાતી",
     code: "gu",  
    },
    {
     no: "55",
     name: "Haitian; Haitian Creole",
     native: "Kreyòl ayisyen",
     code: "ht",  
    },
    {
     no: "56",
     name: "Hausa",
     native: "Hausa, هَوُسَ",
     code: "ha",  
    },
    {
     no: "57",
     name: "Hebrew(modern)",
     native: "עברית",
     code: "he",  
    },
    {
     no: "58",
     name: "Herero",
     native: "Otjiherero",
     code: "hz",  
    },
    {
     no: "59",
     name: "Hindi",
     native: "हिन्दी, हिंदी",
     code: "hi",  
    },
    {
     no: "60",
     name: "Hiri Motu",
     native: "Hiri Motu",
     code: "ho",  
    },
    {
     no: "61",
     name: "Hungarian",
     native: "Magyar",
     code: "hu",  
    },
    {
     no: "62",
     name: "Interlingua",
     native: "Interlingua",
     code: "ia",  
    },
    {
     no: "63",
     name: "Indonesian",
     native: "Bahasa Indonesia",
     code: "id",  
    },
    {
     no: "64",
     name: "Interlingue",
     native: "Originally called Occidental; then Interlingue after WWII",
     code: "ie",  
    },
    {
     no: "65",
     name: "Irish",
     native: "Gaeilge",
     code: "ga",  
    },
    {
     no: "66",
     name: "Igbo",
     native: "Asụsụ Igbo",
     code: "ig",  
    },
    {
     no: "67",
     name: "Inupiaq",
     native: "Iñupiaq, Iñupiatun",
     code: "ik",  
    },
    {
     no: "68",
     name: "Ido",
     native: "Ido",
     code: "io",  
    },
    {
     no: "69",
     name: "Icelandic",
     native: "Íslenska",
     code: "is",  
    },
    {
     no: "70",
     name: "Italian",
     native: "Italiano",
     code: "it",  
    },
    {
     no: "71",
     name: "Inuktitut",
     native: "ᐃᓄᒃᑎᑐᑦ",
     code: "iu",  
    },
    {
     no: "72",
     name: "Japanese",
     native: "日本語 (にほんご／にっぽんご)",
     code: "ja",  
    },
    {
     no: "73",
     name: "Javanese",
     native: "basa Jawa",
     code: "jv",  
    },
    {
     no: "74",
     name: "Kalaallisut; Greenlandic",
     native: "kalaallisut, kalaallit oqaasii",
     code: "kl",  
    },
    {
     no: "75",
     name: "Kannada",
     native: "ಕನ್ನಡ",
     code: "kn",  
    },
    {
     no: "76",
     name: "Kanuri",
     native: "Kanuri",
     code: "kr",  
    },
    {
     no: "77",
     name: "Kashmiri",
     native: "कश्मीरी, كشميري‎",
     code: "ks",  
    },
    {
     no: "78",
     name: "Kazakh",
     native: "Қазақ тілі",
     code: "kk",  
    },
    {
     no: "79",
     name: "Khmer",
     native: "ភាសាខ្មែរ",
     code: "km",  
    },
    {
     no: "80",
     name: "Kikuyu; Gikuyu",
     native: "Gĩkũyũ",
     code: "ki",  
    },
    {
     no: "81",
     name: "Kinyarwanda",
     native: "Ikinyarwanda",
     code: "rw",  
    },
    {
     no: "82",
     name: "Kirghiz; Kyrgyz",
     native: "Кыргызча",
     code: "ky",  
    },
    {
     no: "83",
     name: "Komi",
     native: "коми кыв",
     code: "kv",  
    },
    {
     no: "84",
     name: "Kongo",
     native: "Kikongo",
     code: "kg",  
    },
    {
     no: "85",
     name: "Korean",
     native: "한국어 (韓國語), 조선말 (朝鮮語)",
     code: "ko",  
    },
    {
     no: "86",
     name: "Kurdish",
     native: "Kurdî, کوردی‎",
     code: "ku",  
    },
    {
     no: "87",
     name: "Kwanyama; Kuanyama",
     native: "Kwanyama",
     code: "kj",  
    },
    {
     no: "88",
     name: "Latin",
     native: "latine, lingua latina",
     code: "la",  
    },
    {
     no: "89",
     name: "Luxembourgish; Letzeburgesch",
     native: "Lëtzebuergesch",
     code: "lb",  
    },
    {
     no: "90",
     name: "Luganda",
     native: "Luganda",
     code: "lg",  
    },
    {
     no: "91",
     name: "Lao",
     native: "ພາສາລາວ",
     code: "lo",  
    },
    {
     no: "92",
     name: "Lithuanian",
     native: "lietuvių kalba",
     code: "lt",  
    },
    {
     no: "93",
     name: "Luba-Katanga",
     native: "Luba-Katanga",
     code: "lu",  
    },
    {
     no: "94",
     name: "Latvian",
     native: "latviešu valoda",
     code: "lv",  
    },
    {
     no: "95",
     name: "Manx",
     native: "Gaelg, Gailck",
     code: "gv",  
    },
    {
     no: "96",
     name: "Macedonian",
     native: "македонски јазик",
     code: "mk",  
    },
    {
     no: "97",
     name: "Malagasy",
     native: "Malagasy fiteny",
     code: "mg",  
    },
    {
     no: "98",
     name: "Malay",
     native: "Bahasa Melayu, بهاس ملايو‎",
     code: "ms",  
    },
    {
     no: "99",
     name: "Malayalam",
     native: "മലയാളം",
     code: "ml",  
    },
    {
     no: "100",
     name: "Maltese",
     native: "Malti",
     code: "mt",  
    },
    {
     no: "101",
     name: "Maori",
     native: "te reo Māori",
     code: "mi",  
    },
    {
     no: "102",
     name: "Marathi",
     native: "मराठी",
     code: "mr",  
    },
    {
     no: "103",
     name: "Marshallese",
     native: "Kajin M̧ajeļ",
     code: "mh",  
    },
    {
     no: "104",
     name: "Mongolian",
     native: "Монгол хэл",
     code: "mn",  
    },
    {
     no: "105",
     name: "Nauru",
     native: "Ekakairũ Naoero",
     code: "na",  
    },
    {
     no: "106",
     name: "Navajo; Navaho",
     native: "Diné bizaad, Dinékʼehǰí",
     code: "nv",  
    },
    {
     no: "107",
     name: "Norwegian Bokmål",
     native: "Norsk bokmål",
     code: "nb",  
    },
    {
     no: "108",
     name: "North Ndebele",
     native: "isiNdebele",
     code: "nd",  
    },
    {
     no: "109",
     name: "Nepali",
     native: "नेपाली",
     code: "ne",  
    },
    {
     no: "110",
     name: "Ndonga",
     native: "Owambo",
     code: "ng",  
    },
    {
     no: "111",
     name: "Norwegian Nynorsk",
     native: "Norsk nynorsk",
     code: "nn",  
    },
    {
     no: "112",
     name: "Norwegian",
     native: "Norsk",
     code: "no",  
    },
    {
     no: "113",
     name: "Nuosu",
     native: "ꆈꌠ꒿ Nuosuhxop",
     code: "nr",  
    },
    {
     no: "114",
     name: "South Ndebele",
     native: "isiNdebele",
     code: "nr",  
    },
    {
     no: "115",
     name: "Occitan",
     native: "Occitan",
     code: "oc",  
    },
    {
     no: "116",
     name: "Ojibwe, Ojibwa",
     native: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
     code: "oj",  
    },
    {
     no: "117",
     name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
     native: "ѩзыкъ словѣньскъ",
     code: "cu",  
    },
    {
     no: "118",
     name: "Oromo",
     native: "Afaan Oromoo",
     code: "om",  
    },
    {
     no: "119",
     name: "Oriya",
     native: "ଓଡ଼ିଆ",
     code: "or",  
    },
    {
     no: "120",
     name: "Ossetian, Ossetic",
     native: "ирон æвзаг",
     code: "os",  
    },
    {
     no: "121",
     name: "Panjabi, Punjabi",
     native: "ਪੰਜਾਬੀ, پنجابی‎",
     code: "pa",  
    },
    {
     no: "122",
     name: "Pali",
     native: "पालि",
     code: "pi",  
    },
    {
     no: "123",
     name: "Persian",
     native: "فارسی",
     code: "fa",  
    },
    {
     no: "124",
     name: "Polish",
     native: "polski",
     code: "pl",  
    },
    {
     no: "125",
     name: "Pashto, Pushto",
     native: "پښتو",
     code: "ps",  
    },
    {
     no: "126",
     name: "Portuguese",
     native: "Português",
     code: "pt",  
    },
    {
     no: "127",
     name: "Quechua",
     native: "Runa Simi, Kichwa",
     code: "qu",  
    },
    {
     no: "128",
     name: "Romansh",
     native: "rumantsch grischun",
     code: "rm",  
    },
    {
     no: "129",
     name: "Kirundi",
     native: "kiRundi",
     code: "rn",  
    },
    {
     no: "130",
     name: "Romanian, Moldavian, Moldovan",
     native: "română",
     code: "ro",  
    },
    {
     no: "131",
     name: "Russian",
     native: "русский",
     code: "ru",  
    },
    {
     no: "132",
     name: "Sanskrit",
     native: "संस्कृतम्",
     code: "sa",  
    },
    {
     no: "133",
     name: "Sardinian",
     native: "sardu",
     code: "sc",  
    },
    {
     no: "134",
     name: "Sindhi",
     native: "सिन्धी, سنڌي، سندھی",
     code: "sd",  
    },
    {
     no: "135",
     name: "Northern Sami",
     native: "Davvisámegiella",
     code: "lg",  
    },
    {
     no: "136",
     name: "Samoan",
     native: "gagana fa'a Samoa",
     code: "sm",  
    },
    {
     no: "137",
     name: "Sango",
     native: "yângâ tî sängö",
     code: "sg",  
    },
    {
     no: "138",
     name: "Serbian",
     native: "српски језик",
     code: "sr",  
    },
    {
     no: "139",
     name: "Scottish Gaelic; Gaelic",
     native: "Gàidhlig",
     code: "gd",  
    },
    {
     no: "140",
     name: "Shona",
     native: "chiShona",
     code: "sn",  
    },
    {
     no: "141",
     name: "Sinhala, Sinhalese",
     native: "සිංහල",
     code: "si",  
    },
    {
     no: "142",
     name: "Slovak",
     native: "slovenčina",
     code: "sk",  
    },
    {
     no: "143",
     name: "Slovene",
     native: "slovenščina",
     code: "sl",  
    },
    {
     no: "144",
     name: "Somali",
     native: "Soomaaliga, af Soomaali",
     code: "so",  
    },
    {
     no: "145",
     name: "Southern Sotho",
     native: "Sesotho",
     code: "st",  
    },
    {
     no: "146",
     name: "Spanish; Castilian",
     native: "español, castellano",
     code: "es",  
    },
    {
     no: "147",
     name: "Sundanese",
     native: "Basa Sunda",
     code: "su",  
    },
    {
     no: "148",
     name: "Swahili",
     native: "Kiswahili",
     code: "sw",  
    },
    {
     no: "149",
     name: "Swati",
     native: "SiSwati",
     code: "ss",  
    },
    {
     no: "150",
     name: "Swedish",
     native: "svenska",
     code: "sv",  
    },
    {
     no: "151",
     name: "Tamil",
     native: "தமிழ்",
     code: "ta",  
    },
    {
     no: "152",
     name: "Telugu",
     native: "తెలుగు",
     code: "te",  
    },
    {
     no: "153",
     name: "Tajik",
     native: "тоҷикӣ",
     code: "tg",  
    },
    {
     no: "154",
     name: "Thai",
     native: "ไทย",
     code: "th",  
    },
    {
     no: "155",
     name: "Tigrinya",
     native: "ትግርኛ",
     code: "ti",  
    },
    {
     no: "156",
     name: "Tibetan Standard, Tibetan, Central",
     native: "བོད་ཡིག",
     code: "bo",  
    },
    {
     no: "157",
     name: "Turkmen",
     native: "Türkmen, Түркмен",
     code: "tk",  
    },
    {
     no: "158",
     name: "Tagalog",
     native: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
     code: "tl",  
    },
    {
     no: "159",
     name: "Tswana",
     native: "Setswana",
     code: "tn",  
    },
    {
     no: "160",
     name: "Tonga (Tonga Islands)",
     native: "Faka Tonga",
     code: "to",  
    },
    {
     no: "161",
     name: "Turkish",
     native: "Türkçe",
     code: "tr",  
    },
    {
     no: "162",
     name: "Tsonga",
     native: "Xitsonga",
     code: "ts",  
    },
    {
     no: "163",
     name: "Tatar",
     native: "татар теле",
     code: "tt",  
    },
    {
     no: "164",
     name: "Twi",
     native: "Twi",
     code: "tw",  
    },
    {
     no: "165",
     name: "Tahitian",
     native: "Reo Tahiti",
     code: "ty",  
    },
    {
     no: "166",
     name: "Uighur, Uyghur",
     native: "Uyƣurqə, ئۇيغۇرچە",
     code: "ug",  
    },
    {
     no: "167",
     name: "Ukrainian",
     native: "українська",
     code: "uk",  
    },
    {
     no: "168",
     name: "Urdu",
     native: "اردو",
     code: "ur",  
    },
    {
     no: "169",
     name: "Uzbek",
     native: "Oʻzbek, Ўзбек, أۇزبېك‎",
     code: "uz",  
    },
    {
     no: "170",
     name: "Venda",
     native: "Tshivenḓa",
     code: "ve",  
    },
    {
     no: "171",
     name: "Vietnamese",
     native: "Tiếng Việt",
     code: "vi",  
    },
    {
     no: "172",
     name: "Volapük",
     native: "Volapük",
     code: "vo",  
    },
    {
     no: "173",
     name: "Walloon",
     native: "Walon",
     code: "wa",  
    },
    {
     no: "174",
     name: "Welsh",
     native: "Cymraeg",
     code: "cy",  
    },
    {
     no: "175",
     name: "Wolof",
     native: "Wollof",
     code: "wo",  
    },
    {
     no: "176",
     name: "Western Frisian",
     native: "Frysk",
     code: "fy",  
    },
    {
     no: "177",
     name: "Xhosa",
     native: "isiXhosa",
     code: "xh",  
    },
    {
     no: "178",
     name: "Yiddish",
     native: "ייִדיש",
     code: "yi",  
    },
    {
     no: "179",
     name: "Yoruba",
     native: "Yorùbá",
     code: "yo",  
    },
    {
     no: "180",
     name: "Zhuang, Chuang",
     native: "Saɯ cueŋƅ, Saw cuengh",
     code: "za",  
    },
]